### PR TITLE
Refactor log format for more script-friendly

### PR DESCRIPTION
**Pull request by matsumotory**
- refactor tags
  - `[LOG-ONLY] [VHOST_COUNT]` to `LOG-ONLY-VHOST_COUNT`
  - remove `NOTICE` tag
- change time format
  - `Fri Nov 06 00:29:03 2015` to `2015/11/06 00:29:03`

### CODE REVIEW

**Comment by matsumotory** [comment]
- example

```
2015-11-13 15:35:54 LOG-ONLY-VHOST_COUNT return 503 from blog.matsumoto-r.jp:8080 : 2 / 1 client_ip: 119.170.71.29 uri: /wp-admin/admin-ajax.php filename: /usr/local/apache/htdocs/blog/wp-admin/admin-ajax.php
```

```
2015-11-13 15:39:41 VHOST_COUNT return 503 from blog.matsumoto-r.jp:8080 : 3 / 2 client_ip: 219.118.163.49 uri: /wp-admin/admin-ajax.php filename: /usr/local/apache/htdocs/blog/wp-admin/admin-ajax.php
```

**Comment by matsumotory** [comment]
@atani Please review it.

**Comment by atani** [comment]
@matsumoto-r Thank you :-) Good!

**Comment by matsumotory** [comment]
@atani Thank you for your review. So I'll merge it and release new version after passing tests.

**Pull request merged**
